### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by LeonmanRolls** [ensdomains/governance-web-react#14]
- [x] add random weighting to listing
- [x] loading states
- [x] filter out record that don't have the same resolver address as the domain
- [x] disabled button styling
- [x] all localstorage info should be keyed by claiming address
- [x] cypress tests for all critical paths
- [x] lookup namehashes properly - Jeff
- [x] clicking on the speech bubble selects the delegate
- [x] add error monitoring
- [x] clear up redirect memory leak
- [x] wrong network error
- [x] query string for preselected delegate - Jeff
- [x] twitter default text
- [x] links at the bottom of the page
- [x] mobile allocation flippening
- [x] constitution in address specific localstorage
- [x] Bubble prepopulated delegate to the top 
- [x] Fix grid columns on delegates
- [x] Search for delegates
